### PR TITLE
New scrolling and animation functionality for 8x8 Matrix components

### PR DESCRIPTION
**Pull request by jakekarnes42**
In my personal project, I found the need to scroll images across the 8x8 matrix. I thought I would contribute this work back to the shared library so that everyone can benefit and save from time.

The new functionality has been added to the Matrix8x8 class. The BicolorMatrix8x8 also inherits these changes since it now inherits from the Matrix8x8 class.

The three most important new functions are the following:
1. **horizontal_scroll:** Returns a list of images which appear to scroll from left to right across the input image when displayed on the LED matrix in order.
2. **vertical_scroll:** Returns a list of images which appear to scroll from top to bottom down the input image when displayed on the LED matrix in order.
3. **animate:** Displays each of the input images in order, pausing for a configurable amount of time after each image.

I've tested these changes in my own project where I have about 30 different animations. In that project, I am using a Raspberry Pi B+ and a Bicolor Matrix component. Although the modifications I made should run well on all platforms, I've only tested it with limited hardware.

I've also expanded the example script for the Bicolor Matrix to demonstrate some of the new functionality. 

I would really love to see these changes pulled into the main repository. And if you felt so kind, I would really appreciate being listed as a contributor on the readme page. I'm a college student and it would be a nice boost to my resume to have a documented contribution to a great open source project like this.

### CODE REVIEW

**Comment by matt-land** [comment]
I tested jakekarnes42's code by running both examples. Works.

**Comment by jakekarnes42** [comment]
Can you please take another look at this pull request? It probably has dropped off your radar.

**Comment by tdicola** [comment]
Oh ack sorry yeah haven't had a chance to come back to this one.  I'll grab the backpack matrices and take a look at merging this week.  Thanks!

**Comment by tdicola** [comment]
Apologies agin it took so long for me to review it, but I just had a chance to sit down with the bicolor 8x8 and it works great!  Thanks again for contributing--just merged in the code.  This should be super handy for folks that want to scroll messages, etc. on the display.

**Pull request merged**
